apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlwYXNz
  MYSQL_DATABASE: ZWNvbW1lcmNlX2FwcF9kYXRhYmFzZQ==
  MYSQL_USER: bXlzcWx1c2Vy
  MYSQL_PASSWORD: bXlwYXNz
