apiVersion: v1
kind: Service
metadata:
  name: payment-service-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
  type: ClusterIP
