apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: bakirjacoub/spring-boot-react-ecommerce-app-master-authentication-service:latest
          env:
            - name: DB_HOST
              value: "mysql-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "mysqluser"
            - name: DB_PASS
              value: "mypass"
            - name: DB_SCHEMA
              value: "ecommerce_app_database"
            - name: ACTIVE_PROFILE
              value: "dev"
            - name: PORT
              value: "7005"
