apiVersion: v1
kind: Service
metadata:
  name: authentication-service-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 7005
      targetPort: 7005
  type: ClusterIP
